#!/usr/bin/env python3
"""Point Capacitor's generated android/app/build.gradle at Codemagic's upload keystore.

codemagic.yaml's `android_signing: [seen_upload]` makes the keystore available on the build
machine and exports CM_* environment variables. It does NOT configure Gradle to use them.
Capacitor's generated build.gradle ships no signingConfigs block, so `./gradlew bundleRelease`
produces an UNSIGNED bundle, the build reports success, and Play rejects the upload with
"All uploaded bundles must be signed" after the whole thing has run.

android/ is regenerated by `cap add android` on every build, so this is applied per build
rather than committed — same as the package name and the SDK levels.

Usage:
    patch-android-signing.py <build.gradle>            # apply
    patch-android-signing.py --verify <build.gradle>   # assert only
"""
import re
import sys

SIGNING_BLOCK = '''    signingConfigs {
        release {
            storeFile file(System.getenv("CM_KEYSTORE_PATH"))
            storePassword System.getenv("CM_KEYSTORE_PASSWORD")
            keyAlias System.getenv("CM_KEY_ALIAS")
            keyPassword System.getenv("CM_KEY_PASSWORD")
        }
    }
'''
WIRING = "            signingConfig signingConfigs.release\n"


def apply(path):
    src = open(path).read()
    if "signingConfigs" in src:
        print("signingConfigs already present -- skipping")
        return

    # ORDER MATTERS, and getting it wrong is not obvious.
    #
    # Wire buildTypes.release FIRST, while the only `release {` in the file is the build type.
    # Inserting signingConfigs first creates a second, EARLIER `release {`, and the wiring line
    # then lands inside the signing config itself — referring to the block it sits in. That
    # result is brace-balanced and passes a naive text check, so it looks fine and is not.
    src, n = re.subn(r"(?m)^(        release \{\n)", r"\1" + WIRING, src, count=1)
    if n != 1:
        sys.exit(f"!! buildTypes.release not found in {path}")

    src, n = re.subn(r"(?m)^(android \{\n)", r"\1" + SIGNING_BLOCK, src, count=1)
    if n != 1:
        sys.exit(f"!! android block not found in {path}")

    open(path, "w").write(src)
    print("signingConfigs injected")


def verify(path):
    src = open(path).read()

    build_types = re.search(r"buildTypes \{.*?\n    \}", src, re.S)
    if not build_types or "signingConfig signingConfigs.release" not in build_types.group(0):
        sys.exit("!! signingConfig is not inside buildTypes -- the release build will be unsigned")

    signing = re.search(r"signingConfigs \{.*?\n    \}", src, re.S)
    if not signing:
        sys.exit("!! no signingConfigs block")
    if "signingConfig signingConfigs.release" in signing.group(0):
        sys.exit("!! signingConfig wrongly nested inside signingConfigs (self-referential)")
    if "CM_KEYSTORE_PATH" not in signing.group(0):
        sys.exit("!! signingConfigs does not read the Codemagic keystore variables")

    print("OK -- release build type signs with the upload keystore.")


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)
    if args[0] == "--verify":
        verify(args[1])
    else:
        apply(args[0])
