// Copyright © 2025 Mahiman Singh Rathore. All rights reserved.
//
// hytPrompts.js — the "Practice" ("Have you tried?") prompt bank: small, concrete,
// doable-today acts of kindness across 14 life areas (~40 each), plus an age-banded
// self-care bank for the daily "Self" slot. Deterministic daily selection (date + uid),
// so no server/cron is needed.

export const HYT_AREAS = [
  { id: "work", emoji: "💼", label: "Work life", prompts: [
    "Have you tried… telling a colleague specifically what they did well this week?",
    "Have you tried… making someone a cup of tea without being asked?",
    "Have you tried… greeting the new starter and offering to answer any questions?",
    "Have you tried… thanking the person who quietly keeps the office tidy?",
    "Have you tried… saying good morning to everyone you pass in the corridor?",
    "Have you tried… offering to take a task off a stressed colleague's plate?",
    "Have you tried… praising a teammate's idea out loud in front of the group?",
    "Have you tried… leaving a kind note on a coworker's desk?",
    "Have you tried… asking a quiet colleague what they think before deciding?",
    "Have you tried… crediting someone by name for work you passed on upstream?",
    "Have you tried… checking in on a colleague who seemed a bit flat today?",
    "Have you tried… holding the lift and chatting for a floor or two?",
    "Have you tried… bringing in a little something to share with the team?",
    "Have you tried… replying warmly to that email you'd normally leave curt?",
    "Have you tried… thanking your manager for something helpful they did?",
    "Have you tried… offering to proofread a colleague's tricky document?",
    "Have you tried… saving someone a seat before a busy meeting?",
    "Have you tried… learning the name of someone you see daily but never greet?",
    "Have you tried… covering a small task so a colleague can leave on time?",
    "Have you tried… inviting someone eating alone to join you for lunch?",
    "Have you tried… asking the cleaner how their day is going, and listening?",
    "Have you tried… sharing a useful tip with a colleague who's stuck?",
    "Have you tried… thanking someone who gave you honest feedback lately?",
    "Have you tried… celebrating a teammate's small win in the group chat?",
    "Have you tried… offering your umbrella to a colleague caught in the rain?",
    "Have you tried… tidying the shared kitchen without mentioning it to anyone?",
    "Have you tried… passing on a compliment you overheard about someone?",
    "Have you tried… asking a colleague about their weekend and really hearing it?",
    "Have you tried… volunteering for the job nobody wants, just this once?",
    "Have you tried… reassuring a colleague who's beating themselves up over a mistake?",
    "Have you tried… saying thank you to reception on your way in?",
    "Have you tried… introducing two colleagues who'd get on or help each other?",
    "Have you tried… letting a coworker vent for five minutes without fixing it?",
    "Have you tried… restocking the printer or kettle before someone else has to?",
    "Have you tried… sending a colleague a link you know they'd find useful?",
    "Have you tried… thanking someone from another team for their patience?",
    "Have you tried… asking a colleague if they need anything before you nip out?",
    "Have you tried… acknowledging the person taking the meeting minutes?",
    "Have you tried… wishing a departing coworker well and meaning every word?",
    "Have you tried… telling someone their work made your day easier today?",
  ] },
  { id: "home", emoji: "🏠", label: "Home & family", prompts: [
    "Have you tried… making a family member's bed as a small surprise?",
    "Have you tried… cooking someone's favourite meal without a reason?",
    "Have you tried… putting your phone away and really listening at dinner?",
    "Have you tried… leaving a loving note where a family member will find it?",
    "Have you tried… doing a chore that isn't yours, quietly?",
    "Have you tried… asking a parent to tell you a story from when they were young?",
    "Have you tried… giving someone at home a proper, unhurried hug?",
    "Have you tried… bringing a warm drink to whoever's working hardest right now?",
    "Have you tried… thanking whoever cooked, even if it was a simple meal?",
    "Have you tried… tidying a shared space before anyone asks?",
    "Have you tried… asking a sibling how they're really doing lately?",
    "Have you tried… letting a family member pick tonight's film without a fuss?",
    "Have you tried… reading a bedtime story with all the silly voices?",
    "Have you tried… doing the washing-up so someone else can put their feet up?",
    "Have you tried… texting a relative just to say you're thinking of them?",
    "Have you tried… praising a child for effort rather than the result?",
    "Have you tried… sorting the laundry someone's been dreading?",
    "Have you tried… asking gran or grandad to teach you one of their recipes?",
    "Have you tried… giving your full attention when a child wants to show you something?",
    "Have you tried… making breakfast for the household before they're up?",
    "Have you tried… saying sorry first, before the mood has time to set?",
    "Have you tried… planning a small treat outing everyone would enjoy?",
    "Have you tried… fixing that little thing at home you keep walking past?",
    "Have you tried… telling a family member one thing you admire about them?",
    "Have you tried… taking the bins out before you're reminded?",
    "Have you tried… putting fresh flowers where the whole house can see them?",
    "Have you tried… calling a relative you've not spoken to in a while?",
    "Have you tried… letting a family member sleep in and covering their morning jobs?",
    "Have you tried… asking what would make someone's evening a bit easier?",
    "Have you tried… warming a towel for whoever's next out of the shower?",
    "Have you tried… writing down a happy family memory and sharing it tonight?",
    "Have you tried… giving a pet an extra walk or a good long fuss?",
    "Have you tried… putting away someone else's shoes and coat without a word?",
    "Have you tried… asking a teenager about something they actually care about?",
    "Have you tried… leaving the last biscuit for someone who'd love it?",
    "Have you tried… thanking a family member for something they always do?",
    "Have you tried… starting a jigsaw or game the whole house can dip into?",
    "Have you tried… checking the elderly neighbour is warm and has what they need?",
    "Have you tried… saying goodnight properly, face to face, tonight?",
    "Have you tried… asking everyone one good thing about their day at tea?",
  ] },
  { id: "friends", emoji: "🤝", label: "Friendship", prompts: [
    "Have you tried… texting a friend to say you're grateful for them?",
    "Have you tried… asking a friend how last week's worry turned out?",
    "Have you tried… sending a photo that reminds you of a good day together?",
    "Have you tried… ringing a friend just to hear their voice?",
    "Have you tried… reminding a friend of something brave they once did?",
    "Have you tried… inviting a friend round for a cuppa this week?",
    "Have you tried… replying to that message you've been meaning to answer?",
    "Have you tried… telling a friend exactly why you value them?",
    "Have you tried… checking in on the friend who's gone a bit quiet?",
    "Have you tried… offering to help a friend with something they're dreading?",
    "Have you tried… celebrating a friend's good news properly today?",
    "Have you tried… posting a friend a card just because?",
    "Have you tried… asking a friend for advice to show you trust them?",
    "Have you tried… remembering a date that matters to a friend and marking it?",
    "Have you tried… listening to a friend without reaching for your phone?",
    "Have you tried… planning something to look forward to together?",
    "Have you tried… forgiving a friend for that small thing and letting it go?",
    "Have you tried… sharing a book or song you know a friend would love?",
    "Have you tried… telling a friend you're proud of how far they've come?",
    "Have you tried… turning up for a friend's small event they mentioned?",
    "Have you tried… asking after a friend's parent or partner by name?",
    "Have you tried… making the first move to sort out a little falling-out?",
    "Have you tried… saving a friend the trouble by running an errand for them?",
    "Have you tried… reminiscing with a friend about how you first met?",
    "Have you tried… reaching out to a friend you've lost touch with?",
    "Have you tried… sending a friend a voice note instead of a quick text?",
    "Have you tried… reassuring a friend who's second-guessing themselves?",
    "Have you tried… dropping round a treat when a friend's under the weather?",
    "Have you tried… asking a shy friend along so they don't feel left out?",
    "Have you tried… thanking a friend for a kindness you never acknowledged?",
    "Have you tried… laughing with a friend about an old shared disaster?",
    "Have you tried… offering a friend a lift so you get more time together?",
    "Have you tried… telling a friend that their friendship changed you for the better?",
    "Have you tried… checking a friend got home safe after a night out?",
    "Have you tried… sending encouragement before a friend's big day?",
    "Have you tried… being honest and kind with a friend who asked your opinion?",
    "Have you tried… making time for the friend who always makes time for you?",
    "Have you tried… writing down why a friendship matters and telling them?",
    "Have you tried… giving a friend space without making them feel guilty?",
    "Have you tried… simply asking a friend, how are you really?",
  ] },
  { id: "romance", emoji: "💗", label: "Romantic life", prompts: [
    "Have you tried… telling your partner one thing you fell for early on?",
    "Have you tried… making your partner a drink exactly how they like it?",
    "Have you tried… leaving a loving note for them to find later?",
    "Have you tried… asking about their day before mentioning your own?",
    "Have you tried… holding hands for no reason at all?",
    "Have you tried… planning a small date you know they'd enjoy?",
    "Have you tried… thanking your partner for something they always quietly do?",
    "Have you tried… putting your phone down and giving them your full attention?",
    "Have you tried… saying I love you first thing this morning?",
    "Have you tried… taking on a chore they usually dread?",
    "Have you tried… complimenting your partner on something beyond their looks?",
    "Have you tried… recreating a small moment from when you first got together?",
    "Have you tried… asking what would make them feel most loved this week?",
    "Have you tried… listening to your partner's worry without trying to fix it?",
    "Have you tried… warming their side of the bed on a cold night?",
    "Have you tried… sending them a message mid-day just to say you miss them?",
    "Have you tried… making time to really kiss them hello or goodbye?",
    "Have you tried… remembering something small they mentioned and following up?",
    "Have you tried… apologising properly for that thing you've been avoiding?",
    "Have you tried… cooking together instead of dividing the jobs?",
    "Have you tried… telling your partner you're proud of them today?",
    "Have you tried… giving them a proper shoulder rub after a long day?",
    "Have you tried… letting them choose, and being genuinely happy with it?",
    "Have you tried… putting on a song from early in your relationship?",
    "Have you tried… asking about their dreams for the year ahead?",
    "Have you tried… running them a bath and leaving them in peace?",
    "Have you tried… thanking them for putting up with your off days?",
    "Have you tried… laughing together about something that once drove you mad?",
    "Have you tried… surprising them with their favourite little treat?",
    "Have you tried… saying the specific thing you appreciated them doing today?",
    "Have you tried… sitting close and just being quiet together?",
    "Have you tried… asking how you could support them better right now?",
    "Have you tried… writing down three things you love and reading them aloud?",
    "Have you tried… noticing when they're tired and taking something off them?",
    "Have you tried… greeting them at the door like you're pleased to see them?",
    "Have you tried… reminding your partner of a happy memory you both share?",
    "Have you tried… asking what's been on their mind lately, and truly listening?",
    "Have you tried… doing the small thing they've asked twice, before they ask again?",
    "Have you tried… telling them home feels better because they're in it?",
    "Have you tried… planning a lie-in and breakfast together this weekend?",
  ] },
  { id: "hobbies", emoji: "⚽", label: "Hobbies & sport", prompts: [
    "Have you tried… cheering on someone at your club who's just starting out?",
    "Have you tried… offering to lend a beginner some of your kit for the day?",
    "Have you tried… sharing a tip that once helped you with your hobby?",
    "Have you tried… thanking the volunteer who keeps your club running?",
    "Have you tried… inviting someone who trains alone to join your group?",
    "Have you tried… clapping the slowest finisher as loudly as the first?",
    "Have you tried… helping pack away the kit after the session ends?",
    "Have you tried… complimenting a teammate on how much they've improved?",
    "Have you tried… welcoming a newcomer and showing them the ropes?",
    "Have you tried… passing on a book or gear you no longer use to a beginner?",
    "Have you tried… encouraging someone who wants to give up on a tough day?",
    "Have you tried… thanking your coach or instructor for their patience?",
    "Have you tried… celebrating an opponent's good play, not just your own?",
    "Have you tried… offering to give a clubmate a lift to the next meet?",
    "Have you tried… learning the name of someone you always train beside?",
    "Have you tried… asking a quieter member how they're getting on?",
    "Have you tried… sharing your progress to encourage someone else to start?",
    "Have you tried… tidying the shared equipment so it's ready for the next lot?",
    "Have you tried… giving genuine feedback when someone asks for it kindly?",
    "Have you tried… turning up to support a friend's match or performance?",
    "Have you tried… helping a struggling teammate rather than overtaking them?",
    "Have you tried… thanking whoever laid out the pitch or set up the room?",
    "Have you tried… teaching a younger member one thing you're good at?",
    "Have you tried… congratulating someone who beat you and meaning it?",
    "Have you tried… offering water or a snack to someone who forgot theirs?",
    "Have you tried… posting a kind word about your club online?",
    "Have you tried… checking on a member who's been injured or absent?",
    "Have you tried… slowing your pace to keep a struggling friend company?",
    "Have you tried… praising the referee or umpire for a fair call?",
    "Have you tried… inviting a friend to try your hobby with no pressure?",
    "Have you tried… sharing the good spot, seat or lane rather than keeping it?",
    "Have you tried… writing a thank-you to whoever runs your local group?",
    "Have you tried… helping a beginner untangle a problem you once had?",
    "Have you tried… noticing who's left out and drawing them in?",
    "Have you tried… lending your notes or playlist to someone keen to learn?",
    "Have you tried… staying behind to help a newer member practise?",
    "Have you tried… saying well played to everyone, win or lose?",
    "Have you tried… encouraging a nervous first-timer before they begin?",
    "Have you tried… thanking the group for a session you enjoyed?",
    "Have you tried… offering your spot to someone who's waited longer than you?",
  ] },
  { id: "strangers", emoji: "🌍", label: "Strangers & public", prompts: [
    "Have you tried… letting someone go ahead of you in a queue and meaning it?",
    "Have you tried… holding a door and wishing the person a good day?",
    "Have you tried… smiling warmly at the next stranger you pass?",
    "Have you tried… giving up your seat before anyone has to ask?",
    "Have you tried… helping someone carry a pushchair up the stairs?",
    "Have you tried… telling a stranger you love their coat or their smile?",
    "Have you tried… picking up something a stranger dropped and returning it?",
    "Have you tried… offering directions to someone who looks a little lost?",
    "Have you tried… thanking a bus driver as you step off?",
    "Have you tried… letting a car merge in front of you with a friendly wave?",
    "Have you tried… helping someone reach an item on a high shelf?",
    "Have you tried… making room on the pavement without a hint of sigh?",
    "Have you tried… saying a warm good morning to someone waiting alone?",
    "Have you tried… reassuring a frazzled parent that their child's fine?",
    "Have you tried… offering your umbrella's shelter to someone caught out?",
    "Have you tried… returning a stray trolley for the next person?",
    "Have you tried… complimenting a stranger's dog and asking its name?",
    "Have you tried… letting the tailgating driver past without a fuss?",
    "Have you tried… picking up litter someone else left on the bench?",
    "Have you tried… waiting patiently and warmly while someone counts their change?",
    "Have you tried… asking an older person if they'd like a hand crossing?",
    "Have you tried… giving clear space to a cyclist or wheelchair user?",
    "Have you tried… telling a busker you enjoyed their playing?",
    "Have you tried… holding the lift for the person hurrying towards it?",
    "Have you tried… offering your phone charger to a stranded traveller?",
    "Have you tried… stepping aside so someone with a heavy bag can pass?",
    "Have you tried… reassuring a nervous first-time visitor to your area?",
    "Have you tried… saying thank you to the crossing guard by the school?",
    "Have you tried… letting a family sit together by giving up your seat?",
    "Have you tried… warning a stranger they've dropped their glove or scarf?",
    "Have you tried… helping someone struggling with a heavy door at the shops?",
    "Have you tried… giving a genuine well done to a runner mid-park?",
    "Have you tried… making eye contact and thanking whoever let you pass?",
    "Have you tried… guiding a tourist to the platform they need?",
    "Have you tried… offering the last free table to a stranger with more bags?",
    "Have you tried… telling a parent their little one is being very good?",
    "Have you tried… letting someone with just a few items go before you?",
    "Have you tried… waving a thank-you to the driver who stopped for you?",
    "Have you tried… checking a person sitting alone looks alright?",
    "Have you tried… offering your seat on the train before settling in yours?",
  ] },
  { id: "digital", emoji: "📱", label: "Digital life", prompts: [
    "Have you tried… leaving a kind comment on someone's post today?",
    "Have you tried… replying to that voice note you've been putting off?",
    "Have you tried… sending a good-morning message to someone you've missed?",
    "Have you tried… sharing a small win of a friend's so more people see it?",
    "Have you tried… thanking someone publicly for advice they gave online?",
    "Have you tried… messaging an old contact just to say you were thinking of them?",
    "Have you tried… writing a genuine review for a small business you love?",
    "Have you tried… sending an encouraging note before someone's big day?",
    "Have you tried… replying warmly rather than with just a thumbs-up?",
    "Have you tried… tagging a friend in something you know they'd adore?",
    "Have you tried… checking in on the friend who's gone quiet in the group chat?",
    "Have you tried… correcting misinformation gently instead of piling on?",
    "Have you tried… sending a photo memory to whoever shared that day with you?",
    "Have you tried… congratulating a stranger whose good news came up online?",
    "Have you tried… answering someone's question in a forum patiently?",
    "Have you tried… muting a heated thread rather than adding to the heat?",
    "Have you tried… sending a link that would genuinely help someone you know?",
    "Have you tried… replying to the family group chat you keep skimming past?",
    "Have you tried… thanking a creator whose work brightened your day?",
    "Have you tried… reaching out to someone whose post sounded a bit low?",
    "Have you tried… turning a snappy reply into a kinder one before you send it?",
    "Have you tried… wishing someone a happy birthday with actual words?",
    "Have you tried… sharing helpful local news with a neighbour online?",
    "Have you tried… recommending a friend for a role they'd be brilliant at?",
    "Have you tried… sending a meme that you know will make one person laugh?",
    "Have you tried… praising a colleague in a message their boss can see?",
    "Have you tried… replying to a stranger's honest question with real help?",
    "Have you tried… deleting the comment you were about to post in anger?",
    "Have you tried… voice-noting a friend so they hear the warmth in it?",
    "Have you tried… welcoming a newcomer to an online group you're part of?",
    "Have you tried… sending a photo of something that reminded you of someone?",
    "Have you tried… thanking a mod or admin who keeps a group friendly?",
    "Have you tried… boosting a cause a friend cares about with a share?",
    "Have you tried… asking a distant relative for a video call this week?",
    "Have you tried… replying to that message before it slips your mind again?",
    "Have you tried… complimenting someone's work in the comments, specifically?",
    "Have you tried… sending calm reassurance to someone panicking in a chat?",
    "Have you tried… reconnecting with someone whose post popped up today?",
    "Have you tried… crediting the person whose idea you're about to share?",
    "Have you tried… ending a message with a genuine, specific thank you?",
  ] },
  { id: "transactional", emoji: "🧾", label: "Everyday transactions", prompts: [
    "Have you tried… asking the person at the till how their shift is going?",
    "Have you tried… thanking your delivery driver and wishing them a good round?",
    "Have you tried… having your loyalty card ready so the queue keeps moving?",
    "Have you tried… telling a waiter the meal was lovely, specifically?",
    "Have you tried… saying please and thank you like you really mean it today?",
    "Have you tried… letting the harried cashier know there's no rush?",
    "Have you tried… returning your trolley and passing the next one along?",
    "Have you tried… complimenting the barista on your perfectly made coffee?",
    "Have you tried… leaving a kind word in the feedback box or app?",
    "Have you tried… bagging your own shopping so the cashier can breathe?",
    "Have you tried… greeting the shopkeeper before you start looking around?",
    "Have you tried… thanking the person who restocked the shelf you needed?",
    "Have you tried… being patient with the new trainee learning the till?",
    "Have you tried… telling a manager how helpful their staff member was?",
    "Have you tried… holding the shop door for the delivery driver's trolley?",
    "Have you tried… offering the courier a glass of water on a hot day?",
    "Have you tried… learning the name of the person at your regular café?",
    "Have you tried… saying no worries when your order takes a little longer?",
    "Have you tried… thanking the postie by name when they hand you a parcel?",
    "Have you tried… letting someone with a crying baby go ahead of you?",
    "Have you tried… putting your basket back neatly for the next customer?",
    "Have you tried… praising a small shop online after a good visit?",
    "Have you tried… asking the market stallholder about their best produce today?",
    "Have you tried… reassuring a cashier who's just given the wrong change?",
    "Have you tried… thanking the cleaner tidying the café you're sat in?",
    "Have you tried… wishing the shop staff a good evening as you leave?",
    "Have you tried… telling a tradesperson you appreciated their tidy, careful work?",
    "Have you tried… reporting a fault kindly rather than with a complaint?",
    "Have you tried… saying take your time to a flustered person serving you?",
    "Have you tried… thanking the driver for getting your parcel there in the rain?",
    "Have you tried… asking the pharmacist how their busy morning has been?",
    "Have you tried… moving your car so the delivery van can get by?",
    "Have you tried… giving clear, friendly directions to the parcel drop-off?",
    "Have you tried… telling the hairdresser exactly what you loved about the cut?",
    "Have you tried… letting someone with fewer items go before you at the till?",
    "Have you tried… smiling and greeting the security guard on your way in?",
    "Have you tried… thanking the bin crew if you catch them on your street?",
    "Have you tried… complimenting a small shop on how welcoming it feels?",
    "Have you tried… being warm to the call handler sorting out your query?",
    "Have you tried… leaving a note of thanks out for a regular delivery driver?",
  ] },
  { id: "neighbourhood", emoji: "🏘️", label: "Neighbourhood", prompts: [
    "Have you tried… saying good morning to a neighbour you usually walk past?",
    "Have you tried… putting your neighbour's bin out for them?",
    "Have you tried… leaving a friendly note for someone new on the street?",
    "Have you tried… offering to collect shopping for an elderly neighbour?",
    "Have you tried… returning a lost parcel to the right door?",
    "Have you tried… sweeping the shared path outside your building?",
    "Have you tried… baking a little extra to share with next door?",
    "Have you tried… learning the name of someone you see every day?",
    "Have you tried… holding the door and having a proper chat?",
    "Have you tried… offering your spare parking space to a visitor?",
    "Have you tried… watering a neighbour's plants while they're away?",
    "Have you tried… picking up litter on your own street this morning?",
    "Have you tried… lending a tool to someone mid-project next door?",
    "Have you tried… inviting a neighbour round for a cup of tea?",
    "Have you tried… tucking a kind card through a lonely neighbour's door?",
    "Have you tried… helping someone carry heavy bags up the stairs?",
    "Have you tried… clearing leaves from a neighbour's doorstep?",
    "Have you tried… sharing your umbrella with someone caught in the rain?",
    "Have you tried… giving directions warmly to someone looking lost?",
    "Have you tried… dropping spare veg from your garden next door?",
    "Have you tried… offering to walk a neighbour's dog today?",
    "Have you tried… saying thank you to your local postie?",
    "Have you tried… greeting the shopkeeper you see most days by name?",
    "Have you tried… leaving a good review for a small local business?",
    "Have you tried… offering your seat to someone at the bus stop?",
    "Have you tried… checking in on a neighbour during the heat?",
    "Have you tried… fixing a wobbly fence panel you both share?",
    "Have you tried… returning a stray ball to the children next door?",
    "Have you tried… gritting the shared steps on an icy morning?",
    "Have you tried… welcoming a new family with a small local guide?",
    "Have you tried… offering to jump-start a neighbour's flat battery?",
    "Have you tried… sharing your wifi password with someone stuck offline?",
    "Have you tried… tidying the communal hallway a little?",
    "Have you tried… letting a neighbour know their light was left on?",
    "Have you tried… bringing a neighbour's washing in before the rain?",
    "Have you tried… saying hello to someone eating lunch alone nearby?",
    "Have you tried… offering a lift to someone heading your way?",
    "Have you tried… planting something cheerful by the front step for all to see?",
    "Have you tried… thanking a local volunteer for their time?",
    "Have you tried… leaving spare seeds on the wall for passers-by?",
  ] },
  { id: "money", emoji: "💷", label: "Money life", prompts: [
    "Have you tried… paying for the coffee of the person behind you?",
    "Have you tried… rounding up your bill and leaving the change as a tip?",
    "Have you tried… popping a few coins in a charity box today?",
    "Have you tried… treating a friend to lunch just because?",
    "Have you tried… giving your loose change to a busker you enjoyed?",
    "Have you tried… setting up a small monthly gift to a cause you love?",
    "Have you tried… slipping a note into a birthday card for a young one?",
    "Have you tried… donating a bag of tins to the local food bank?",
    "Have you tried… covering a friend's bus fare when they're short?",
    "Have you tried… buying a spare sandwich for someone who's hungry?",
    "Have you tried… leaving a generous tip for a tired waiter?",
    "Have you tried… paying off a stranger's small layaway or tab?",
    "Have you tried… gifting a book you loved to someone who'd enjoy it?",
    "Have you tried… sponsoring a friend's charity run today?",
    "Have you tried… giving unused vouchers to someone who needs them?",
    "Have you tried… donating to a local school's fundraiser?",
    "Have you tried… quietly settling a colleague's coffee round?",
    "Have you tried… posting a small gift card to cheer someone up?",
    "Have you tried… paying a little extra at a market to a small maker?",
    "Have you tried… giving your bottle deposit refunds to charity?",
    "Have you tried… buying flowers for someone who never gets any?",
    "Have you tried… forgiving a small debt a friend has forgotten?",
    "Have you tried… treating your parents to their favourite takeaway?",
    "Have you tried… dropping coins in an expiring meter for a stranger?",
    "Have you tried… donating your old glasses to a sight charity?",
    "Have you tried… chipping in for a colleague's leaving gift?",
    "Have you tried… buying a raffle ticket at the community fair?",
    "Have you tried… gifting a warm drink to someone sleeping rough?",
    "Have you tried… paying for a child's ice cream on a hot day?",
    "Have you tried… giving a bigger tip to your regular hairdresser?",
    "Have you tried… donating to a crowdfunder for someone in need?",
    "Have you tried… buying the Big Issue and having a chat?",
    "Have you tried… leaving grocery money with a struggling friend, no strings?",
    "Have you tried… gifting your unused gym pass to a friend?",
    "Have you tried… putting a surprise treat on a loved one's account?",
    "Have you tried… donating spare foreign coins to an airport charity box?",
    "Have you tried… buying extra pet food for the animal shelter?",
    "Have you tried… paying for a stranger's stamp at the post office?",
    "Have you tried… tipping the delivery driver a little more today?",
    "Have you tried… gifting a small plant to brighten someone's desk?",
  ] },
  { id: "care", emoji: "🫶", label: "Care life", prompts: [
    "Have you tried… texting a grieving friend just to say you're thinking of them?",
    "Have you tried… dropping a home-cooked meal round to someone unwell?",
    "Have you tried… sitting quietly with someone who's having a hard day?",
    "Have you tried… offering to do the school run for a stressed parent?",
    "Have you tried… sending a card to someone in hospital?",
    "Have you tried… asking a carer how they are, and really listening?",
    "Have you tried… picking up a prescription for someone poorly?",
    "Have you tried… offering to sit with someone so their carer can rest?",
    "Have you tried… bringing soup to a friend with a cold?",
    "Have you tried… remembering the anniversary of someone's loss with a note?",
    "Have you tried… offering a lift to a hospital appointment?",
    "Have you tried… doing the washing-up for a friend who's overwhelmed?",
    "Have you tried… saying the name of someone's loved one who has died?",
    "Have you tried… leaving flowers on a struggling friend's doorstep?",
    "Have you tried… phoning a lonely relative for a proper catch-up?",
    "Have you tried… offering to walk the dog of someone recovering?",
    "Have you tried… making a cup of tea for someone in tears?",
    "Have you tried… sending a voice note to someone too tired to text back?",
    "Have you tried… asking what do you need instead of guessing?",
    "Have you tried… stocking a poorly friend's fridge with easy meals?",
    "Have you tried… offering to babysit so new parents can nap?",
    "Have you tried… sitting with someone anxious in a waiting room?",
    "Have you tried… dropping off tissues and biscuits to a grieving neighbour?",
    "Have you tried… reminding a struggling friend they're doing their best?",
    "Have you tried… taking the bins out for someone who's unwell?",
    "Have you tried… sending a gentle no-need-to-reply message?",
    "Have you tried… offering to run errands for a housebound friend?",
    "Have you tried… bringing a warm blanket to someone feeling low?",
    "Have you tried… checking in on a carer who rarely gets a break?",
    "Have you tried… holding space for someone's story without fixing it?",
    "Have you tried… leaving a thermos of soup for a night-shift friend?",
    "Have you tried… offering to tidy up for someone too poorly to manage?",
    "Have you tried… posting a small comfort parcel to someone far away?",
    "Have you tried… reminding someone grieving to eat something today?",
    "Have you tried… staying on the phone in silence with a lonely friend?",
    "Have you tried… offering to read to someone whose eyes are tired?",
    "Have you tried… dropping a get-well note to a colleague off sick?",
    "Have you tried… making space for a friend to cry without apology?",
    "Have you tried… bringing a hot water bottle to someone in pain?",
    "Have you tried… simply asking a struggling person to sit with you a while?",
  ] },
  { id: "learning", emoji: "📚", label: "Learning & mentoring", prompts: [
    "Have you tried… teaching someone a small skill you take for granted?",
    "Have you tried… encouraging a nervous learner with genuine praise?",
    "Have you tried… sharing a helpful article with someone starting out?",
    "Have you tried… showing a colleague a shortcut that saves them time?",
    "Have you tried… offering to proofread a student's application today?",
    "Have you tried… answering a beginner's question without any judgement?",
    "Have you tried… lending a book that changed how you think?",
    "Have you tried… helping a child sound out a tricky word?",
    "Have you tried… teaching someone how to cook a favourite dish?",
    "Have you tried… sharing your notes with a struggling classmate?",
    "Have you tried… showing a neighbour how to use their new phone?",
    "Have you tried… offering to mock-interview a friend job hunting?",
    "Have you tried… explaining a bill or form to someone confused by it?",
    "Have you tried… praising the effort, not just the result?",
    "Have you tried… recording a short how-to for someone learning?",
    "Have you tried… helping an older relative video-call the family?",
    "Have you tried… passing on a craft you love to someone curious?",
    "Have you tried… sharing an online course link with a keen learner?",
    "Have you tried… sitting with a child while they practise reading?",
    "Have you tried… teaching someone a few words in another language?",
    "Have you tried… showing a beginner how to change a bike tyre?",
    "Have you tried… offering feedback that builds someone up, kindly?",
    "Have you tried… helping a friend write a tricky email?",
    "Have you tried… demonstrating a knitting stitch to someone stuck?",
    "Have you tried… encouraging a shy person to share their idea?",
    "Have you tried… teaching a young one how to tie their laces?",
    "Have you tried… mentoring someone through their first week at work?",
    "Have you tried… explaining a hobby's basics to a curious friend?",
    "Have you tried… sharing a mistake you learned from, so others can too?",
    "Have you tried… helping someone practise for a driving test?",
    "Have you tried… showing a colleague where to find the answer themselves?",
    "Have you tried… celebrating a learner's small win out loud?",
    "Have you tried… teaching someone to bake bread from scratch?",
    "Have you tried… offering to tutor a neighbour's child for an hour?",
    "Have you tried… passing on a gardening tip to a new grower?",
    "Have you tried… helping someone set up their first budget?",
    "Have you tried… showing a friend how to fix something themselves?",
    "Have you tried… encouraging someone to keep going when they doubt themselves?",
    "Have you tried… sharing a podcast that taught you something today?",
    "Have you tried… writing a warm reference for someone who deserves it?",
  ] },
  { id: "nature", emoji: "🐦", label: "Nature & animals", prompts: [
    "Have you tried… leaving water out for birds on a hot day?",
    "Have you tried… scattering seeds for the birds this morning?",
    "Have you tried… making a little hedgehog gap in your fence?",
    "Have you tried… picking up litter on a walk in the park?",
    "Have you tried… planting something the bees will love?",
    "Have you tried… letting a patch of grass grow wild for insects?",
    "Have you tried… topping up a bird bath in the sunshine?",
    "Have you tried… rescuing a worm stranded on the path after rain?",
    "Have you tried… hanging fat balls out for the birds?",
    "Have you tried… leaving a dish of water out for passing dogs?",
    "Have you tried… putting out a shallow bowl for thirsty hedgehogs?",
    "Have you tried… building a small bug hotel from twigs?",
    "Have you tried… floating a cork in the pond so bees can drink safely?",
    "Have you tried… clearing plastic from a hedgerow or stream?",
    "Have you tried… planting a pollinator-friendly window box?",
    "Have you tried… leaving fallen leaves as shelter for creatures?",
    "Have you tried… giving your neighbour's cat a fuss and a stroke?",
    "Have you tried… donating an old towel to an animal shelter?",
    "Have you tried… checking under the car for cats before driving off?",
    "Have you tried… saving a bee with a spoon of sugar water?",
    "Have you tried… putting up a nesting box for spring?",
    "Have you tried… growing herbs on the sill for butterflies?",
    "Have you tried… giving a rescue dog an extra long walk?",
    "Have you tried… leaving windfall apples out for the birds?",
    "Have you tried… freeing a moth trapped indoors, gently?",
    "Have you tried… planting a tree or shrub for the future?",
    "Have you tried… topping up the garden pond in dry weather?",
    "Have you tried… making a pinecone feeder for the birds?",
    "Have you tried… lifting a snail off the pavement to safety?",
    "Have you tried… sprinkling mealworms out for the robins?",
    "Have you tried… leaving a wild corner untouched for wildlife?",
    "Have you tried… donating old blankets to a wildlife rescue?",
    "Have you tried… checking bonfire piles for hedgehogs before lighting?",
    "Have you tried… planting spring bulbs for the bees to come?",
    "Have you tried… keeping cats in at dusk to protect small wildlife?",
    "Have you tried… filling a hanging feeder for the tits and finches?",
    "Have you tried… giving your houseplants a proper water and clean?",
    "Have you tried… leaving out nesting material like wool scraps?",
    "Have you tried… reporting an injured animal to a local rescue?",
    "Have you tried… simply pausing to thank a tree for its shade?",
  ] },
  { id: "legacy", emoji: "🕯️", label: "Legacy life", prompts: [
    "Have you tried… writing down one piece of advice you'd want a younger you to hear?",
    "Have you tried… planting a tree that others will sit under one day?",
    "Have you tried… recording a favourite family story before it's forgotten?",
    "Have you tried… writing a letter for a loved one to open years from now?",
    "Have you tried… teaching a child a recipe passed down to you?",
    "Have you tried… labelling old photos with names and dates?",
    "Have you tried… sharing a grandparent's saying with the next generation?",
    "Have you tried… starting a memory jar for the family to fill?",
    "Have you tried… writing down the story behind a treasured heirloom?",
    "Have you tried… planting bulbs that will return every spring?",
    "Have you tried… passing on a skill your parents taught you?",
    "Have you tried… noting three things you're grateful for, for someone to find?",
    "Have you tried… recording a voice message telling someone why they matter?",
    "Have you tried… beginning a family recipe book today?",
    "Have you tried… writing your own kindness pledge for the year?",
    "Have you tried… sharing a lesson a hard time taught you?",
    "Have you tried… planting a herb garden a friend can keep growing?",
    "Have you tried… writing a thank-you to a teacher who shaped you?",
    "Have you tried… saving a piece of advice in a card for a new baby?",
    "Have you tried… starting a tradition your family can keep for years?",
    "Have you tried… mapping out your family tree while elders can help?",
    "Have you tried… donating a favourite book to a little free library?",
    "Have you tried… writing down what you hope people remember you for?",
    "Have you tried… teaching a young one a song you grew up with?",
    "Have you tried… leaving a kind note tucked inside a library book?",
    "Have you tried… passing an old tool on to someone who'll use it well?",
    "Have you tried… writing a short letter of forgiveness, even unsent?",
    "Have you tried… sharing the meaning behind your name with family?",
    "Have you tried… planting a fruit tree for children yet to taste it?",
    "Have you tried… recording an elder telling their favourite memory?",
    "Have you tried… writing down a value you hope to pass on?",
    "Have you tried… gathering old letters into one keepsake box?",
    "Have you tried… teaching someone a game your family always played?",
    "Have you tried… noting the story of how your parents met?",
    "Have you tried… leaving encouraging words for a stranger to find?",
    "Have you tried… starting a journal for a child to read when grown?",
    "Have you tried… sharing a piece of wisdom with someone younger today?",
    "Have you tried… pressing a flower to keep from a special day?",
    "Have you tried… writing out the traditions you never want to lose?",
    "Have you tried… planting something now that you may never see fully grown?",
  ] },
];

// Self-care ("Self life") slot — age-banded (13–17 / 18–49 / 50+).
export const SELF_META = { id: "self", emoji: "🌤️", label: "Self care" };
export const SELF_CARE = {
  teen: [
    "Have you tried… putting your phone in another room 30 minutes before you sleep tonight?",
    "Have you tried… speaking to yourself the way you'd speak to your best mate?",
    "Have you tried… taking three slow breaths before you open that stressful message?",
    "Have you tried… drinking a glass of water and stretching after a long stint of homework?",
    "Have you tried… writing down one thing you did okay today, however small?",
    "Have you tried… muting an account that makes you feel rubbish about yourself?",
    "Have you tried… stepping outside for five minutes of fresh air between revision?",
    "Have you tried… letting yourself feel a big feeling without deciding it's the whole story?",
    "Have you tried… going to bed 30 minutes earlier tonight, as a gift to tomorrow-you?",
    "Have you tried… asking one person for help with something that's been weighing on you?",
    "Have you tried… reminding yourself that a bad test doesn't make you a bad person?",
    "Have you tried… putting on a song you love and moving about for one whole track?",
    "Have you tried… noticing that everyone's highlight reel online hides their messy days too?",
    "Have you tried… giving yourself permission to log off and rest without guilt?",
    "Have you tried… texting a friend just to say hi, with nothing you need from them?",
    "Have you tried… breaking that big task into three smaller, less scary steps?",
    "Have you tried… eating something proper when you notice you're getting snappy or foggy?",
    "Have you tried… letting yourself not have your whole future figured out yet?",
    "Have you tried… taking a proper break instead of pushing through when your brain is fried?",
    "Have you tried… writing your worries on paper so they stop rattling round your head?",
    "Have you tried… being patient with your body while it's busy growing and changing?",
    "Have you tried… saying no to plans when you honestly just need a quiet night in?",
    "Have you tried… unfollowing the comparison and following things that make you laugh?",
    "Have you tried… naming what you're actually feeling instead of just 'fine'?",
    "Have you tried… celebrating finishing something, not just getting the top mark?",
    "Have you tried… sitting with a cuppa and doing nothing at all for ten minutes?",
    "Have you tried… reminding yourself it's okay to outgrow friendships as you change?",
    "Have you tried… stretching your shoulders and neck after hunching over your phone?",
    "Have you tried… asking for a bit of quiet when the house feels too loud to think?",
    "Have you tried… letting a good cry happen instead of bottling it all up?",
    "Have you tried… planning one small thing to look forward to this week?",
    "Have you tried… reminding yourself that you don't have to be liked by everyone?",
    "Have you tried… charging your phone outside your bedroom so mornings feel calmer?",
    "Have you tried… doing one kind thing for yourself the way you would for a friend?",
    "Have you tried… stepping away from a group chat that's stressing you out for a bit?",
    "Have you tried… noticing five things you can see right now when your mind races?",
    "Have you tried… wearing the comfy clothes that make you feel most like yourself?",
    "Have you tried… forgiving yourself for a mistake the way time eventually will anyway?",
    "Have you tried… getting outside in daylight to help your body know it's daytime?",
    "Have you tried… reminding yourself that asking for help is brave, not weak?",
  ],
  adult: [
    "Have you tried… taking your full lunch break away from your desk today?",
    "Have you tried… going to bed 30 minutes earlier tonight, as a gift to tomorrow-you?",
    "Have you tried… speaking to yourself today the way you'd speak to a friend?",
    "Have you tried… turning off work notifications once you've clocked off?",
    "Have you tried… saying no to one thing this week so you can properly rest?",
    "Have you tried… drinking a glass of water before your third coffee of the morning?",
    "Have you tried… stepping outside for a short walk between meetings?",
    "Have you tried… letting 'good enough' be enough on something small today?",
    "Have you tried… putting your phone down and giving your eyes a proper rest?",
    "Have you tried… asking for help before you're completely running on empty?",
    "Have you tried… blocking out 20 minutes in your diary that's just for you?",
    "Have you tried… noticing three things that went right today, not just what didn't?",
    "Have you tried… stretching your back and shoulders after a long stint sitting down?",
    "Have you tried… letting the washing-up wait so you can sit down for ten minutes?",
    "Have you tried… texting someone you've been meaning to catch up with for ages?",
    "Have you tried… taking a few slow breaths before you walk into that meeting?",
    "Have you tried… leaving work on time today, even if the list isn't finished?",
    "Have you tried… eating a proper meal at the table instead of at your keyboard?",
    "Have you tried… protecting one evening this week with absolutely no plans?",
    "Have you tried… reminding yourself that rest is productive, not a reward you earn?",
    "Have you tried… putting your feet up for ten minutes without your phone nearby?",
    "Have you tried… saying how you actually feel instead of 'I'm fine, just busy'?",
    "Have you tried… getting outside in daylight first thing to set up your day?",
    "Have you tried… writing tomorrow's worries down tonight so your mind can switch off?",
    "Have you tried… letting yourself off the hook for something you didn't get to?",
    "Have you tried… putting your favourite song on and moving for one whole track?",
    "Have you tried… setting a gentle boundary with someone who drains your energy?",
    "Have you tried… booking the appointment you've been quietly putting off?",
    "Have you tried… having a proper lie-in this weekend without setting an alarm?",
    "Have you tried… noticing when you're doom-scrolling and closing the app for now?",
    "Have you tried… asking for the day to be a little kinder, starting with your break?",
    "Have you tried… making a cup of tea and drinking it while it's still hot?",
    "Have you tried… celebrating finishing something instead of racing to the next thing?",
    "Have you tried… going for a walk without a podcast, just to hear your own thoughts?",
    "Have you tried… letting someone do you a favour without feeling you owe them?",
    "Have you tried… switching your phone to greyscale to make it less of a pull tonight?",
    "Have you tried… doing one thing today purely because it brings you joy?",
    "Have you tried… taking your annual leave instead of letting the days quietly expire?",
    "Have you tried… unclenching your jaw and dropping your shoulders right now?",
    "Have you tried… ending the day by naming one thing you're grateful for?",
  ],
  older: [
    "Have you tried… taking a gentle stroll somewhere green when the weather's kind?",
    "Have you tried… ringing an old friend just to hear a familiar voice today?",
    "Have you tried… sitting with a cuppa and savouring it slowly, with no rush?",
    "Have you tried… doing a few gentle stretches when you first get up in the morning?",
    "Have you tried… letting yourself rest in the afternoon without a shred of guilt?",
    "Have you tried… writing down a memory that still makes you smile?",
    "Have you tried… saying yes to an invitation, even if part of you wants to stay in?",
    "Have you tried… speaking to yourself as kindly as you would to an old friend?",
    "Have you tried… opening the window for some fresh air and a bit of daylight?",
    "Have you tried… taking a moment to notice the birdsong on your way past the garden?",
    "Have you tried… reaching out first when a day feels a little quiet or lonely?",
    "Have you tried… keeping up with something you love, just for the joy of it?",
    "Have you tried… drinking a little more water across the day, in small sips?",
    "Have you tried… sharing a story from your life with someone younger who'd love it?",
    "Have you tried… pottering in the garden or with a plant on the windowsill?",
    "Have you tried… letting today be gentle and unhurried, with nothing to prove?",
    "Have you tried… booking that check-up you've been meaning to sort out?",
    "Have you tried… sitting somewhere sunny for a few minutes with your eyes closed?",
    "Have you tried… learning one small new thing, just to keep the mind curious?",
    "Have you tried… putting on music from your younger years and letting it lift you?",
    "Have you tried… taking the stairs slowly today, at your own comfortable pace?",
    "Have you tried… writing a note to someone to tell them they matter to you?",
    "Have you tried… giving yourself credit for all you've weathered over the years?",
    "Have you tried… planning a small outing to look forward to this week?",
    "Have you tried… sitting quietly with your thoughts and letting the day settle?",
    "Have you tried… asking a neighbour round for a cuppa and a proper natter?",
    "Have you tried… moving your body a little each day, however gently, to stay supple?",
    "Have you tried… letting go of a worry that isn't really yours to carry?",
    "Have you tried… looking through old photographs and savouring the good times?",
    "Have you tried… being patient with your body on the days it moves more slowly?",
    "Have you tried… joining something local so a familiar face becomes part of your week?",
    "Have you tried… making a proper meal you enjoy and eating it without hurry?",
    "Have you tried… noticing one small beautiful thing on your walk today?",
    "Have you tried… reminding yourself your days still hold plenty of purpose?",
    "Have you tried… accepting a helping hand as graciously as you'd offer one?",
    "Have you tried… getting a good night's rest by winding down a little earlier?",
    "Have you tried… reflecting on what you're proud of, not just what's left to do?",
    "Have you tried… stepping outside for a breath of air even for just five minutes?",
    "Have you tried… keeping a regular date in the diary with someone you love?",
    "Have you tried… letting yourself simply be, without needing to be busy?",
  ],
};

export function ageBandFor(age) {
  if (age != null && age < 18) return "teen";
  if (age != null && age >= 50) return "older";
  return "adult";
}

// ── deterministic daily selection ─────────────────────────────────────────────
export function hytHash(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) >>> 0;
  return h;
}
export function todayKey(d = new Date()) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

// Whole days since the epoch, in local time — the counter that walks the area rotation.
function dayNumber(date) {
  return Math.floor(new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime() / 86400000);
}

// Today's two: [kindness (one of the 14 areas, a different one each day), self (age-banded
// self-care)]. The kindness area steps by one whole area per day so the rotation visits all
// 14 in turn rather than repeating at random; the starting point differs per user.
// `swaps[slot]` (0 or 1) shifts to the next prompt — the caller allows one swap per day.
export function pickDaily({ uid = "anon", date = new Date(), swaps = {}, ageBand = "adult" }) {
  const day = todayKey(date);
  const area = HYT_AREAS[(dayNumber(date) + hytHash(uid)) % HYT_AREAS.length];
  const selfList = SELF_CARE[ageBand] || SELF_CARE.adult;

  const pickFrom = (list, slot) => {
    const offset = Math.min(1, swaps[slot] ?? 0);
    const idx = (hytHash(`${uid}|${day}|${slot}`) + offset) % list.length;
    return list[idx];
  };

  return [
    { slot: "kindness", areaId: area.id, emoji: area.emoji, label: area.label, text: pickFrom(area.prompts, "kindness") },
    { slot: "self", areaId: SELF_META.id, emoji: SELF_META.emoji, label: SELF_META.label, text: pickFrom(selfList, "self") },
  ];
}
