// Copyright © 2025 Mahiman Singh Rathore. All rights reserved.
// /api/lifehacks.js — Daily life hack tips generated by Claude, cached until midnight.
//
// Requires: ANTHROPIC_API_KEY env var
// Falls back to curated static hacks when the key is absent.

import Anthropic from "@anthropic-ai/sdk";

// ── Static fallback (shown when Claude is unavailable) ────────────────────────

const FALLBACK_HACKS = [
  {
    area: "Mind",
    areaEmoji: "🧠",
    subArea: "Focus",
    subAreaEmoji: "🎯",
    title: "The 2-Minute Focus Reset",
    hack: "When your mind is scattered, name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. Do it slowly. You'll feel your attention snap back within 30 seconds.",
    why: "This sensory scan interrupts the brain's default-mode network — the part responsible for mind-wandering — and forces it into present-moment awareness.",
  },
  {
    area: "Body",
    areaEmoji: "💪",
    subArea: "Cooking",
    subAreaEmoji: "🍳",
    title: "The Wooden Spoon Trick",
    hack: "Rest a wooden spoon across the top of any boiling pot. The water will never boil over again. Works on pasta, rice, potatoes — anything.",
    why: "Wood doesn't conduct heat, so it destabilises the rising bubbles before they can form the foam layer that spills over the edge.",
  },
  {
    area: "Relationships",
    areaEmoji: "❤️",
    subArea: "Communication",
    subAreaEmoji: "💬",
    title: "Swap 'But' for 'And'",
    hack: "In any disagreement, replace the word 'but' with 'and'. Instead of 'I hear you, but I think...' say 'I hear you, and I also think...' The conversation shifts completely.",
    why: "'But' cancels everything said before it — the other person stops listening the moment they hear it. 'And' signals that both views can coexist, which keeps people receptive.",
  },
  {
    area: "Work",
    areaEmoji: "💼",
    subArea: "Productivity",
    subAreaEmoji: "⚡",
    title: "Write Tomorrow's First Task Tonight",
    hack: "Before you close your laptop each day, write one sentence: the single first thing you will do tomorrow. Put it on a sticky note on your keyboard or phone screen.",
    why: "Decision fatigue peaks in the morning. Removing that first choice means you start with momentum instead of staring at a blank to-do list.",
  },
  {
    area: "Finance",
    areaEmoji: "💰",
    subArea: "Saving",
    subAreaEmoji: "🏦",
    title: "The 48-Hour Rule",
    hack: "Add any non-essential purchase over £20 to a notes app wishlist instead of buying it. Wait exactly 48 hours. If you still want it, buy it guilt-free. Most of the time, you won't.",
    why: "Impulse purchases are driven by a dopamine spike that fades within hours — not genuine need. The delay separates real desire from momentary want.",
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function secondsUntilMidnight() {
  const now = new Date();
  const midnight = new Date(now);
  midnight.setHours(24, 0, 0, 0);
  return Math.max(60, Math.floor((midnight - now) / 1000));
}

function todayString() {
  return new Date().toISOString().split("T")[0]; // YYYY-MM-DD
}

// ── Main handler ──────────────────────────────────────────────────────────────

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");

  const today = todayString();
  const ttl = secondsUntilMidnight();

  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    res.setHeader("Cache-Control", `public, s-maxage=${ttl}, stale-while-revalidate=3600`);
    return res.status(200).json({ date: today, hacks: FALLBACK_HACKS, source: "fallback" });
  }

  try {
    const client = new Anthropic({ apiKey });

    const response = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2048,
      messages: [{
        role: "user",
        content: `Today is ${today}. Generate exactly 5 daily life hacks for the "Seen" wellbeing app — one per life area.

Rules for each hack:
- Give it a memorable, specific name (e.g. "The Wooden Spoon Trick", "The 48-Hour Rule")
- Be CONCRETE and immediately actionable — something a person can try today
- Avoid generic advice like "drink more water" or "exercise regularly" — be specific and surprising
- The "why" must explain the actual science, psychology, or logic — not just restate the tip
- Pick a DIFFERENT sub-area each day by varying based on today's date: ${today}

Life areas and sub-areas to choose from (pick one sub-area per area):
1. Mind 🧠 → Focus, Stress, Sleep, Memory, Creativity, Clarity, Anxiety, Decision-making
2. Body 💪 → Cooking, Exercise, Nutrition, Energy, Rest, Hydration, Posture, Digestion
3. Relationships ❤️ → Communication, Conflict, Friendship, Family, Kindness, Listening, Boundaries, Gratitude
4. Work 💼 → Productivity, Meetings, Email, Planning, Deep Work, Breaks, Procrastination, Organisation
5. Finance 💰 → Saving, Budgeting, Spending, Habits, Investing, Debt, Shopping, Subscriptions

Return ONLY valid JSON with no markdown fences:
{
  "date": "${today}",
  "hacks": [
    {
      "area": "Mind",
      "areaEmoji": "🧠",
      "subArea": "Sleep",
      "subAreaEmoji": "😴",
      "title": "The Warm Sock Trick",
      "hack": "Put on a pair of warm socks 30 minutes before bed...",
      "why": "Warm feet cause blood vessels to dilate, which signals your brain to lower core body temperature — the exact trigger for sleep onset."
    }
  ]
}`,
      }],
    });

    const text = response.content[0]?.text || "";
    const raw = text.match(/\{[\s\S]*\}/)?.[0];
    if (!raw) throw new Error("Claude returned no JSON object");

    const data = JSON.parse(raw);
    if (!Array.isArray(data.hacks) || data.hacks.length < 5) throw new Error("Incomplete hacks array");

    res.setHeader("Cache-Control", `public, s-maxage=${ttl}, stale-while-revalidate=3600`);
    return res.status(200).json({ date: today, hacks: data.hacks, source: "claude" });

  } catch (err) {
    console.error("LifeHacks API error:", err.message);
    // Short retry window so a transient failure recovers quickly
    res.setHeader("Cache-Control", "public, s-maxage=300, stale-while-revalidate=600");
    return res.status(200).json({ date: today, hacks: FALLBACK_HACKS, source: "fallback" });
  }
}
