// Copyright © 2025 Mahiman Singh Rathore. All rights reserved.
// /api/lifehacks.js — Daily life hack tips generated by Claude, cached until midnight.
//
// Requires: ANTHROPIC_API_KEY env var
// Falls back to 5 rotating curated sets (one per day-of-cycle) when the key is absent.

import Anthropic from "@anthropic-ai/sdk";

// ── 5 rotating fallback sets (used when Claude is unavailable) ────────────────
// The active set is chosen by: Math.floor(Date.parse(today) / 86400000) % 5

const FALLBACK_SETS = [
  // ── Set 0: Focus / Cooking / Communication / Productivity / Saving ──────────
  [
    {
      area: "Mind", areaEmoji: "🧠", subArea: "Focus", subAreaEmoji: "🎯",
      title: "The 2-Minute Focus Reset",
      hack: "When your mind is scattered, name 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste. Do it slowly. You'll feel your attention snap back within 30 seconds.",
      why: "This sensory scan interrupts the brain's default-mode network — the part responsible for mind-wandering — and forces it into present-moment awareness.",
    },
    {
      area: "Body", areaEmoji: "💪", subArea: "Cooking", subAreaEmoji: "🍳",
      title: "The Wooden Spoon Trick",
      hack: "Rest a wooden spoon across the top of any boiling pot. The water will never boil over again. Works on pasta, rice, potatoes — anything.",
      why: "Wood doesn't conduct heat, so it destabilises the rising bubbles before they can form the foam layer that spills over the edge.",
    },
    {
      area: "Relationships", areaEmoji: "❤️", subArea: "Communication", subAreaEmoji: "💬",
      title: "Swap 'But' for 'And'",
      hack: "In any disagreement, replace the word 'but' with 'and'. Instead of 'I hear you, but I think...' say 'I hear you, and I also think...' The conversation shifts completely.",
      why: "'But' cancels everything said before it — the other person stops listening the moment they hear it. 'And' signals that both views can coexist, which keeps people receptive.",
    },
    {
      area: "Work", areaEmoji: "💼", subArea: "Productivity", subAreaEmoji: "⚡",
      title: "Write Tomorrow's First Task Tonight",
      hack: "Before you close your laptop each day, write one sentence: the single first thing you will do tomorrow. Put it on a sticky note on your keyboard or phone screen.",
      why: "Decision fatigue peaks in the morning. Removing that first choice means you start with momentum instead of staring at a blank to-do list.",
    },
    {
      area: "Finance", areaEmoji: "💰", subArea: "Saving", subAreaEmoji: "🏦",
      title: "The 48-Hour Rule",
      hack: "Add any non-essential purchase over £20 to a notes app wishlist instead of buying it. Wait exactly 48 hours. If you still want it, buy it guilt-free. Most of the time, you won't.",
      why: "Impulse purchases are driven by a dopamine spike that fades within hours — not genuine need. The delay separates real desire from momentary want.",
    },
    {
      area: "Home", areaEmoji: "🏡", subArea: "Organisation", subAreaEmoji: "📦",
      title: "The One-Touch Rule",
      hack: "When you pick something up, put it where it belongs — not somewhere temporary. The rule: every object gets touched only once before it reaches its home. No surfaces allowed to be transit zones.",
      why: "Clutter accumulates almost entirely from 'temporary' placements that become permanent. The one-touch rule eliminates the second step by making 'put it away' the default, not the exception.",
    },
    {
      area: "Digital", areaEmoji: "📱", subArea: "Notifications", subAreaEmoji: "🔔",
      title: "The Morning Phone Delay",
      hack: "For the first 30 minutes after you wake up, don't touch your phone. Leave it in another room or face down. Start your morning in your own head, not inside someone else's agenda.",
      why: "Checking your phone first thing floods your brain with cortisol before you've set any intention for the day. The first 30 minutes establish the cognitive tone for everything that follows — protect them.",
    },
    {
      area: "Weird & Wonderful", areaEmoji: "🪄", subArea: "Kitchen", subAreaEmoji: "🫙",
      title: "The Rubber Band Lid Grip",
      hack: "When you can't open a stubborn jar, wrap a wide rubber band once around the lid. One rotation. The jar will open first try, every time — no muscle, no towel, no swearing required.",
      why: "The lid isn't stuck because of force — it's stuck because your hand slips on smooth metal. The rubber band increases friction by a factor of 3–4, eliminating slip entirely. It's the grip, not the strength.",
    },
  ],

  // ── Set 1: Sleep / Energy / Listening / Deep Work / Budgeting ───────────────
  [
    {
      area: "Mind", areaEmoji: "🧠", subArea: "Sleep", subAreaEmoji: "😴",
      title: "The 4-7-8 Breathing Method",
      hack: "Breathe in through your nose for 4 seconds, hold for 7, exhale slowly through your mouth for 8. Do 4 cycles. It works on stressed, jet-lagged, and wired minds alike.",
      why: "The extended exhale activates your parasympathetic nervous system — the 'rest and digest' mode. The 7-second hold builds CO₂ tolerance, slowing your heart rate and priming the body for sleep.",
    },
    {
      area: "Body", areaEmoji: "💪", subArea: "Energy", subAreaEmoji: "⚡",
      title: "The Cold Water Face Plunge",
      hack: "When you're sluggish mid-afternoon, fill a bowl or sink with cold water and submerge your face for 15–30 seconds. Your energy will spike faster than any coffee.",
      why: "Cold water on the face triggers the mammalian dive reflex, immediately slowing heart rate and redirecting blood to vital organs. The resulting rush is your body 'waking up' at a cellular level.",
    },
    {
      area: "Relationships", areaEmoji: "❤️", subArea: "Listening", subAreaEmoji: "👂",
      title: "The Parrot Pause",
      hack: "When someone finishes speaking, silently repeat their last three words in your head before you respond. You'll give a better reply, and they'll feel genuinely heard — often for the first time in a while.",
      why: "Most people are composing their response while the other person is still talking. The pause forces actual listening and stops you hijacking the topic, which is the number one complaint people have in conversations.",
    },
    {
      area: "Work", areaEmoji: "💼", subArea: "Deep Work", subAreaEmoji: "🔬",
      title: "The Phone-in-Another-Room Rule",
      hack: "When starting a focused task, physically put your phone in a different room — not face-down, not silenced, in another room. Completely out of sight and reach.",
      why: "Research at UTSA found that your smartphone drains cognitive capacity just by being visible, even when switched off. The brain devotes processing power to resisting the urge to check it.",
    },
    {
      area: "Finance", areaEmoji: "💰", subArea: "Budgeting", subAreaEmoji: "📊",
      title: "The 50/50 Windfall Split",
      hack: "Every time money arrives unexpectedly — a bonus, a refund, a cash gift — split it exactly 50/50 immediately. Half to savings or debt, half to spend guilt-free on whatever you want.",
      why: "Willpower battles over windfalls are always lost eventually. Pre-committing to a rule before the money arrives bypasses the debate entirely. You still enjoy it — just half, not all.",
    },
    {
      area: "Home", areaEmoji: "🏡", subArea: "Lighting", subAreaEmoji: "💡",
      title: "The Colour Temperature Switch",
      hack: "From around 7pm, switch off overhead lights and use only lamps or warm bulbs (2700K or lower). Avoid bright white or blue-tinted lighting entirely. Even 1 hour of this dramatically improves your sleep.",
      why: "Blue-wavelength light suppresses melatonin production by up to 85%. Overhead lighting mimics the midday sun — exactly what your circadian rhythm reads as 'stay awake.' Warm floor lamps bypass this response entirely.",
    },
    {
      area: "Digital", areaEmoji: "📱", subArea: "Screen Time", subAreaEmoji: "📊",
      title: "The Greyscale Trick",
      hack: "Switch your phone to greyscale mode (Settings → Accessibility → Display). Browse everything the same but in black and white. Most people naturally reduce screen time by 30% within 24 hours without trying.",
      why: "Colour is one of the primary dopamine triggers in app design — every red badge, vivid thumbnail, and neon button is engineered to grab attention. Remove the colour and apps become far less compelling.",
    },
    {
      area: "Weird & Wonderful", areaEmoji: "🪄", subArea: "Cables", subAreaEmoji: "🔌",
      title: "The Bread Clip Cable Label",
      hack: "Those small plastic bread clips? Write the name of each cable on one with a biro and clip it around the wire at the plug end. Free, permanent, and instantly readable — no cable will ever be a mystery again.",
      why: "The tabs are exactly the right size for a standard cable, have a flat surface that takes ink, and grip snugly without slipping. They've been the perfect cable label for decades — nobody told you.",
    },
  ],

  // ── Set 2: Memory / Posture / Conflict / Procrastination / Spending ──────────
  [
    {
      area: "Mind", areaEmoji: "🧠", subArea: "Memory", subAreaEmoji: "🗂️",
      title: "The Spaced Repetition Rule",
      hack: "When you learn something you want to remember, review it after 1 day, then 3 days, then 7, then 21. Four reviews in a month and it'll stick for years without further effort.",
      why: "Memory works via the forgetting curve — you lose information rapidly, then more slowly. Reviewing at the exact moment of near-forgetting forces your brain to reconstruct the memory, strengthening it each time.",
    },
    {
      area: "Body", areaEmoji: "💪", subArea: "Posture", subAreaEmoji: "🧍",
      title: "The Doorframe Stretch",
      hack: "Every time you walk through a doorframe today, pause for 10 seconds: place both forearms on either side, one foot forward, and lean gently through. Hold, breathe, continue.",
      why: "Sitting shortens the pectoralis minor muscle and internally rotates the shoulders forward, causing the classic hunched posture. This stretch directly counteracts that — and takes just 10 seconds.",
    },
    {
      area: "Relationships", areaEmoji: "❤️", subArea: "Conflict", subAreaEmoji: "🤝",
      title: "The 24-Hour Draft Rule",
      hack: "When you're about to send an angry email, text, or DM, write it out in full — then save it as a draft. Don't send it for 24 hours. Usually you'll delete it. Sometimes you'll edit it heavily.",
      why: "Anger is a fast emotion with a slow half-life. The initial message is written from cortisol and adrenaline. The version you write 24 hours later uses your prefrontal cortex instead.",
    },
    {
      area: "Work", areaEmoji: "💼", subArea: "Procrastination", subAreaEmoji: "⏰",
      title: "The 2-Minute Kickoff",
      hack: "For any task you're avoiding, make a deal with yourself: just do 2 minutes of it. Set a timer. You're allowed to stop when it goes off. Almost every time, you'll keep going past the timer.",
      why: "Starting is psychologically more costly than continuing. The 2-minute commitment lowers the activation energy enough to get you into flow. Once you're in, inertia takes over.",
    },
    {
      area: "Finance", areaEmoji: "💰", subArea: "Spending", subAreaEmoji: "🛍️",
      title: "The Receipt Photo Rule",
      hack: "After any purchase over £10, take a photo of the receipt and your face showing how you feel about buying it. Review all the photos at the end of the month.",
      why: "Purchases feel abstract once they're made. The photo creates a concrete record with emotional context. Seeing it forces you to confront spending patterns in a visceral way that bank statements never do.",
    },
    {
      area: "Home", areaEmoji: "🏡", subArea: "Clutter", subAreaEmoji: "🗃️",
      title: "The 30-Day Box Method",
      hack: "Put a cardboard box near your front door. For the next 30 days, whenever you encounter something you don't use, love, or need, put it in the box. At 30 days, seal it and donate without opening it.",
      why: "Decluttering decisions are mentally expensive in the moment. The box defers each decision to a single donation event while giving a 30-day cooling-off period. If you haven't retrieved it, you didn't need it.",
    },
    {
      area: "Digital", areaEmoji: "📱", subArea: "Social Media", subAreaEmoji: "👆",
      title: "The Doom-Scroll Interrupt",
      hack: "Move your social apps into a folder on the last page of your home screen, and give the folder a long name like 'Check This Later'. The two extra taps plus reading the folder name is enough friction to break the autopilot scroll reflex.",
      why: "70% of phone pickups happen without a conscious decision to check anything specific. Adding a tiny friction point converts an unconscious habit into a deliberate choice — and most of the time, you won't bother.",
    },
    {
      area: "Weird & Wonderful", areaEmoji: "🪄", subArea: "Cleaning", subAreaEmoji: "🧹",
      title: "The Walnut Wood Fix",
      hack: "Rub a raw walnut directly on any scratch in wooden furniture. Let the natural oils sit for 5 minutes, then buff with a cloth. The scratch visibly disappears or reduces by 90% — no product, no cost.",
      why: "Walnuts contain natural oils that absorb into the exposed dry wood fibres in the scratch, re-staining them close to the surrounding colour. The effect is identical to expensive commercial wood repair products.",
    },
  ],

  // ── Set 3: Creativity / Digestion / Kindness / Email / Subscriptions ─────────
  [
    {
      area: "Mind", areaEmoji: "🧠", subArea: "Creativity", subAreaEmoji: "💡",
      title: "The Morning Pages Method",
      hack: "Set your alarm 20 minutes early. Before you check your phone, write 3 handwritten pages of anything — rambling thoughts, worries, ideas, nonsense. Don't read them back. Just write, then close the notebook.",
      why: "Writing before the critical mind fully wakes up accesses looser, more associative thought patterns. The process drains 'mental static' — the recurring noise that blocks original thinking throughout the day.",
    },
    {
      area: "Body", areaEmoji: "💪", subArea: "Digestion", subAreaEmoji: "🌿",
      title: "The 20-Minute Before-Seconds Rule",
      hack: "Serve yourself one plate at dinner. If you want more, wait exactly 20 minutes before getting seconds. Most of the time the craving will have vanished. Get a timer if needed.",
      why: "Satiety signals travel via the vagus nerve from the gut to the brain, but they take 20 minutes to register. You feel full 20 minutes after you are actually full. The pause catches that delay.",
    },
    {
      area: "Relationships", areaEmoji: "❤️", subArea: "Kindness", subAreaEmoji: "🌟",
      title: "The Specific Compliment",
      hack: "Swap generic compliments for ultra-specific ones. Not 'you're great at your job' but 'the way you handled that tense moment by reframing the question was genuinely impressive.' Try one today.",
      why: "Generic compliments are easy to dismiss as politeness. A specific observation proves you were paying close attention, which carries real social weight — it signals the person is worth watching.",
    },
    {
      area: "Work", areaEmoji: "💼", subArea: "Email", subAreaEmoji: "📧",
      title: "The One-Touch Inbox Rule",
      hack: "When you open an email, make a decision immediately: reply now (if under 2 minutes), schedule it, delegate it, or delete it. Never close an email to 'come back to it later' without acting on it.",
      why: "Re-reading the same email 4–6 times without acting on it is one of the biggest hidden time-wasters in knowledge work. The cost isn't just the re-read — it's the mental weight of unresolved tasks.",
    },
    {
      area: "Finance", areaEmoji: "💰", subArea: "Subscriptions", subAreaEmoji: "📱",
      title: "The Annual Audit Hour",
      hack: "Once a year, open your bank statement and go through every recurring charge line by line. For each one: 'Did I use this more than twice last month?' If not, cancel it today — right then, not later.",
      why: "Subscription services are designed to be invisible once purchased. The average person underestimates their subscription spend by 2.5× because small charges accumulate below conscious awareness.",
    },
    {
      area: "Home", areaEmoji: "🏡", subArea: "Morning Routine", subAreaEmoji: "☀️",
      title: "The Bed-First Rule",
      hack: "Make your bed within 5 minutes of getting up, every single day. Not neatly — just pulled straight with the pillow placed. Don't negotiate with yourself about it. It takes 90 seconds.",
      why: "A made bed signals 'the day has started' to your brain and creates a small completion win before 8am. Research consistently links this single habit to higher task completion rates throughout the rest of the day.",
    },
    {
      area: "Digital", areaEmoji: "📱", subArea: "Focus Mode", subAreaEmoji: "⏱️",
      title: "The App Timeout Rule",
      hack: "Set a daily screen-time limit of 20 minutes for your top two distraction apps. When the limit hits, don't override it — let the lockout run. The discomfort of hitting the wall is entirely the point.",
      why: "App limits work through loss aversion: once you're tracking usage, you become protective of the remaining minutes. The lockout forces a moment of reflection: 'was that time worth what I gave up?'",
    },
    {
      area: "Weird & Wonderful", areaEmoji: "🪄", subArea: "Travel", subAreaEmoji: "✈️",
      title: "The Ice Cube Melt Test",
      hack: "Before a trip, leave a cup of ice cubes in your freezer. When you return, if they've melted and refrozen into a single blob, there was a power cut while you were away — and anything perishable should be treated as unsafe.",
      why: "Ice that melts and re-solidifies has passed through liquid phase, meaning freezer temperature exceeded 0°C. A tray of intact separate cubes confirms the cold chain was never broken — a simple, free food safety check.",
    },
  ],

  // ── Set 4: Stress / Hydration / Gratitude / Meetings / Investing ─────────────
  [
    {
      area: "Mind", areaEmoji: "🧠", subArea: "Stress", subAreaEmoji: "🌊",
      title: "The STOP Technique",
      hack: "When stress peaks, run this 4-step reset: Stop what you're doing. Take one slow breath. Observe what you're feeling — name it specifically ('I feel overwhelmed because of X'). Proceed, choosing your next action deliberately.",
      why: "Naming an emotion ('affect labelling') reduces activity in the amygdala — the brain's alarm centre — within seconds. Putting words to a feeling moves processing from the reactive brain to the reasoning brain.",
    },
    {
      area: "Body", areaEmoji: "💪", subArea: "Hydration", subAreaEmoji: "💧",
      title: "The Pre-Meal Glass Rule",
      hack: "Drink one full glass of water before every meal — not with the meal, before it. Put the glass on the table while you're cooking or serving as a visual cue. Make it non-negotiable.",
      why: "Thirst is frequently misread as hunger. Starting each meal with water reduces caloric intake by ~13% on average and improves kidney function, joint lubrication, and cognitive clarity.",
    },
    {
      area: "Relationships", areaEmoji: "❤️", subArea: "Gratitude", subAreaEmoji: "💌",
      title: "The 3-Good-Things Text",
      hack: "Tonight, text one person three specific things you genuinely appreciate about them. No occasion required, no reciprocation expected. Don't frame it as a question — just send it.",
      why: "Expressed gratitude is one of the highest-effect-size interventions in positive psychology. Both sender and receiver experience measurable mood lifts for 24–72 hours. Saying it aloud amplifies the effect vs. private journalling.",
    },
    {
      area: "Work", areaEmoji: "💼", subArea: "Meetings", subAreaEmoji: "📋",
      title: "The One-Sentence Meeting Test",
      hack: "Before joining or starting any meeting, write one sentence: 'This meeting succeeds when ____.' Share it at the start. If nobody can finish the sentence, the meeting probably shouldn't happen.",
      why: "Meeting costs are invisible — nobody sees the combined hourly rate in the room. A single success criterion makes the cost real and the purpose clear, which either sharpens the meeting or eliminates it.",
    },
    {
      area: "Finance", areaEmoji: "💰", subArea: "Investing", subAreaEmoji: "📈",
      title: "The Round-Up Rule",
      hack: "Set up automatic round-ups on your bank account or use an app that rounds every purchase to the nearest £1 and transfers the difference to a savings pot. Set it once and forget it.",
      why: "Micro-saving works because it operates below the psychological loss-aversion threshold. A £0.73 round-up to £1 is imperceptible spending-wise but compounds to hundreds a year — without a single conscious decision.",
    },
    {
      area: "Home", areaEmoji: "🏡", subArea: "Air Quality", subAreaEmoji: "🌬️",
      title: "The Morning Window",
      hack: "Open at least one window for 10 minutes every morning — even in winter. While the kettle boils, the shower heats, whatever. Just 10 minutes of fresh air exchange makes a measurable difference to how alert you feel.",
      why: "Indoor CO₂ levels rise overnight as you breathe in a closed space. Even sub-dangerous CO₂ elevation measurably impairs decision-making, alertness, and mood. A brief air exchange resets this quickly at no cost.",
    },
    {
      area: "Digital", areaEmoji: "📱", subArea: "Sleep Hygiene", subAreaEmoji: "🌙",
      title: "The Bedroom Charging Ban",
      hack: "Charge your phone in the kitchen or hallway — never your bedroom. Buy a cheap bedside alarm clock for a few pounds. The average person checks their phone 3 times during the night if it's within arm's reach.",
      why: "Every night-time phone check triggers a burst of light and mental activation that fragments deep sleep. 'Just checking the time' always becomes something else. Physical distance is the only intervention that fully works.",
    },
    {
      area: "Weird & Wonderful", areaEmoji: "🪄", subArea: "Laundry", subAreaEmoji: "👕",
      title: "The Dry Towel Trick",
      hack: "When you need laundry dried quickly, add one completely dry bath towel into the dryer with the damp clothes. It reduces drying time by roughly 25% — no settings change, no extra energy cycle needed.",
      why: "Drying slows once the air inside the drum becomes saturated with moisture. The dry towel acts as a humidity sponge, absorbing that moisture and keeping the drying environment efficient for longer.",
    },
  ],
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function secondsUntilMidnight() {
  const now = new Date();
  const midnight = new Date(now);
  midnight.setHours(24, 0, 0, 0);
  return Math.max(60, Math.floor((midnight - now) / 1000));
}

function todayString() {
  return new Date().toISOString().split("T")[0]; // YYYY-MM-DD
}

function fallbackForDate(dateStr) {
  const dayIndex = Math.floor(Date.parse(dateStr) / 86400000) % FALLBACK_SETS.length;
  return FALLBACK_SETS[dayIndex];
}

// ── Main handler ──────────────────────────────────────────────────────────────

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");

  const today = todayString();
  const ttl = secondsUntilMidnight();

  const apiKey = process.env.ANTHROPIC_API_KEY;

  if (!apiKey) {
    res.setHeader("Cache-Control", `public, s-maxage=${ttl}, stale-while-revalidate=60`);
    return res.status(200).json({ date: today, hacks: fallbackForDate(today), source: "fallback" });
  }

  try {
    const client = new Anthropic({ apiKey });

    const response = await client.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2048,
      messages: [{
        role: "user",
        content: `Today is ${today}. Generate exactly 8 daily life hacks for the "Seen" wellbeing app — one per life area.

Rules for each hack:
- Give it a memorable, specific name (e.g. "The Wooden Spoon Trick", "The 48-Hour Rule")
- Be CONCRETE and immediately actionable — something a person can try today
- Avoid generic advice like "drink more water" or "exercise regularly" — be specific and surprising
- The "why" must explain the actual science, psychology, or logic — not just restate the tip
- Pick a DIFFERENT sub-area each day by varying based on today's date: ${today}

Life areas and sub-areas to choose from (pick one sub-area per area):
1. Mind 🧠 → Focus, Stress, Sleep, Memory, Creativity, Clarity, Anxiety, Decision-making
2. Body 💪 → Cooking, Exercise, Nutrition, Energy, Rest, Hydration, Posture, Digestion
3. Relationships ❤️ → Communication, Conflict, Friendship, Family, Kindness, Listening, Boundaries, Gratitude
4. Work 💼 → Productivity, Meetings, Email, Planning, Deep Work, Breaks, Procrastination, Organisation
5. Finance 💰 → Saving, Budgeting, Spending, Habits, Investing, Debt, Shopping, Subscriptions
6. Home 🏡 → Organisation, Cleaning, Lighting, Clutter, Morning Routine, Air Quality, Sleep Space, Storage
7. Digital 📱 → Screen Time, Notifications, Social Media, Focus Mode, Sleep Hygiene, Privacy, App Habits, Digital Detox
8. Weird & Wonderful 🪄 → Kitchen, Cleaning, Cables, Travel, Laundry, DIY, Shopping, Shortcuts

Return ONLY valid JSON with no markdown fences:
{
  "date": "${today}",
  "hacks": [
    {
      "area": "Mind",
      "areaEmoji": "🧠",
      "subArea": "Sleep",
      "subAreaEmoji": "😴",
      "title": "The Warm Sock Trick",
      "hack": "Put on a pair of warm socks 30 minutes before bed...",
      "why": "Warm feet cause blood vessels to dilate, which signals your brain to lower core body temperature — the exact trigger for sleep onset."
    }
  ]
}`,
      }],
    });

    const text = response.content[0]?.text || "";
    const raw = text.match(/\{[\s\S]*\}/)?.[0];
    if (!raw) throw new Error("Claude returned no JSON object");

    const data = JSON.parse(raw);
    if (!Array.isArray(data.hacks) || data.hacks.length < 8) throw new Error("Incomplete hacks array");

    res.setHeader("Cache-Control", `public, s-maxage=${ttl}, stale-while-revalidate=60`);
    return res.status(200).json({ date: today, hacks: data.hacks, source: "claude" });

  } catch (err) {
    console.error("LifeHacks API error:", err.message);
    res.setHeader("Cache-Control", "public, s-maxage=300, stale-while-revalidate=60");
    return res.status(200).json({ date: today, hacks: fallbackForDate(today), source: "fallback" });
  }
}
